# docker/docker-compose.yml

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bank-default-api
    ports:
      - "8000:8000"
    networks:
      - bank_net

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    container_name: bank-default-api-test
    command: ["pytest", "tests/test_api.py"]
    networks:
      - bank_net
    depends_on:
      - api

networks:
  bank_net:
    driver: bridge

## ✅ Launch instructions (PowerShell or terminal)
## cd "D:\Mon Portfolio Projets\Prediction-payments-default-finance\docker"
# docker-compose up --build


# Launching : docker-compose -f docker/docker-compose.yml up --build 